### ISSUE TITLE
Properly annotate breaking changes for 2.x release

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/http-signature-header#41]
https://github.com/digitalbazaar/http-signature-header/blob/master/CHANGELOG.md#200---2021-02-25

None of the changes in 2.x are labelled as breaking.  Since it was a major release, I would expect that at least one of them is a breaking change.

**Comment by davidlehn** [comment]
Fixed in https://github.com/digitalbazaar/http-signature-header/pull/42.
Is a release needed for this?
